name: Data Product Spec Registration

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: "Environment (dev or prod)"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  run-spec-registration:
    runs-on: ubuntu-latest
    env:
      # Databricks Service Principal Client ID
      DATABRICKS_CLIENT_ID: "{% raw %} ${{ secrets.DATABRICKS_CLIENT_ID }} {% endraw %}"
      # Databricks Workspace URL
      DATABRICKS_HOST: "{% raw %} ${{ vars.DATABRICKS_HOST_VAR }} {% endraw %}"
      # ID of Databricks service principal
      BUNDLE_VAR_SERVICE_PRINCIPAL_ID: "{% raw %} ${{ vars.SERVICE_PRINCIPAL_ID_VAR }} {% endraw %}"
      DATABRICKS_AUTH_TYPE: github-oidc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run Spec Registration
        run: uv run data_product_spec_reg